#!/usr/bin/env python3
"""Patch curl files for iOS cross-compilation."""
import sys, re, os

config_path = os.path.abspath(sys.argv[1])
deps_dir = os.path.dirname(os.path.dirname(os.path.dirname(config_path)))
curl_src = os.path.join(deps_dir, 'curl-src', 'lib')

# --- Patch curl_config.h ---
# curl's CMake uses check_type_size which stores result in SIZEOF_CURL_OFF_T.
# curl_setup.h then derives CURL_SIZEOF_CURL_OFF_T from SIZEOF_CURL_OFF_T.
# Both must be patched to 8 (long long size on all iOS arm64 devices).
txt = open(config_path).read()
txt = re.sub(r'#define SIZEOF_CURL_OFF_T \d+', '#define SIZEOF_CURL_OFF_T 8', txt)
txt = re.sub(r'#define CURL_SIZEOF_CURL_OFF_T \d+', '#define CURL_SIZEOF_CURL_OFF_T 8', txt)
txt = re.sub(r'#define CURL_SUFFIX_CURL_OFF_T\s+\S+', '#define CURL_SUFFIX_CURL_OFF_T LL', txt)
txt = re.sub(r'#define CURL_TYPEOF_CURL_OFF_T\s+\S+', '#define CURL_TYPEOF_CURL_OFF_T long long', txt)
txt = re.sub(r'struct timeval \{[^}]+\};', '/* timeval: provided by iOS SDK */', txt, flags=re.DOTALL)
for undef in ['HAVE_STRUCT_TIMEVAL', 'HAVE_RECV', 'HAVE_SEND']:
    txt = re.sub(r'/\* #undef ' + undef + r' \*/', f'#define {undef} 1', txt)
    if undef not in txt:
        txt += f'\n#define {undef} 1\n'
if 'SIZEOF_CURL_OFF_T' not in txt:
    txt += '\n#define SIZEOF_CURL_OFF_T 8\n'
txt += """
#ifndef RECV_TYPE_ARG1
#define RECV_TYPE_ARG1 int
#define RECV_TYPE_ARG2 void *
#define RECV_TYPE_ARG3 size_t
#define RECV_TYPE_ARG4 int
#define RECV_TYPE_RETV ssize_t
#define SEND_TYPE_ARG1 int
#define SEND_TYPE_ARG2 const void *
#define SEND_TYPE_ARG3 size_t
#define SEND_TYPE_ARG4 int
#define SEND_TYPE_RETV ssize_t
#endif
"""
open(config_path, 'w').write(txt)
print(f"Patched: {config_path}")

# --- Patch curl_setup.h ---
# Prepend defines that cannot be overridden by curl_config.h.
# Use #undef then #define (not #ifndef) so curl_config.h can't override us.
setup_path = os.path.join(curl_src, 'curl_setup.h')
if os.path.exists(setup_path):
    raw = open(setup_path, 'rb').read()
    s = raw.replace(b'\r\n', b'\n').decode('utf-8')

    # Remove previous patch attempt
    if 'Vitra iOS' in s:
        s = re.sub(r'/\* Vitra iOS.*?End Vitra iOS overrides \*/\n\n', '', s, flags=re.DOTALL)

    # Prepend — use #undef to guarantee our values survive curl_config.h redefines
    prefix = """/* Vitra iOS: force 64-bit curl_off_t for iOS arm64 cross-compilation */
#undef  SIZEOF_CURL_OFF_T
#define SIZEOF_CURL_OFF_T 8
#undef  CURL_SIZEOF_CURL_OFF_T
#define CURL_SIZEOF_CURL_OFF_T 8
#undef  CURL_TYPEOF_CURL_OFF_T
#define CURL_TYPEOF_CURL_OFF_T long long
#undef  CURL_SUFFIX_CURL_OFF_T
#define CURL_SUFFIX_CURL_OFF_T LL
#undef  CURL_SUFFIX_CURL_OFF_TU
#define CURL_SUFFIX_CURL_OFF_TU ULL
#ifndef OS
#define OS "iOS"
#endif
/* End Vitra iOS */

"""
    s = prefix + s
    open(setup_path, 'w').write(s)
    print(f"Patched and verified: {setup_path}")
else:
    print(f"WARNING: not found: {setup_path}")

# --- Patch curl_setup_once.h: guard timeval ---
once_path = os.path.join(curl_src, 'curl_setup_once.h')
if os.path.exists(once_path):
    raw = open(once_path, 'rb').read()
    s = raw.replace(b'\r\n', b'\n').decode('utf-8')
    s = re.sub(
        r'(struct timeval \{[^}]+\};)',
        r'#ifndef _TIMEVAL_DEFINED\n\1\n#endif',
        s
    )
    open(once_path, 'w').write(s)
    print(f"Patched: {once_path}")
else:
    print(f"WARNING: not found: {once_path}")


# --- Patch curl/system.h (generated) ---
# This is the public header that sets CURL_SIZEOF_CURL_OFF_T.
# It's generated by cmake in the build include dir.
# system.h is in curl-src/include/curl/ (source tree), not curl-build
system_h_path = os.path.join(deps_dir, 'curl-src', 'include', 'curl', 'system.h')
print(f"Looking for curl/system.h at: {system_h_path}")
if os.path.exists(system_h_path):
    raw = open(system_h_path, 'rb').read()
    s = raw.replace(b'\r\n', b'\n').decode('utf-8')
    # Force CURL_SIZEOF_CURL_OFF_T to 8 everywhere
    s = re.sub(r'#define CURL_SIZEOF_CURL_OFF_T \d+', '#define CURL_SIZEOF_CURL_OFF_T 8', s)
    s = re.sub(r'#define CURL_TYPEOF_CURL_OFF_T\s+\S+', '#define CURL_TYPEOF_CURL_OFF_T long long', s)
    s = re.sub(r'#define CURL_SUFFIX_CURL_OFF_T\s+\S+', '#define CURL_SUFFIX_CURL_OFF_T LL', s)
    open(system_h_path, 'w').write(s)
    print(f"Patched: {system_h_path}")
else:
    print(f"WARNING: curl/system.h not found at {system_h_path}")



# --- Patch ws.c: fix stub curl_ws_meta signature in #else block ---
# When USE_WEBSOCKETS is not defined, curl 8.8.0 has a bug: the stub function
# uses internal type `struct Curl_easy *` but the public header declares `CURL *`.
# Fix the stub to use CURL* to match the public declaration.
ws_path = os.path.join(curl_src, 'ws.c')
if os.path.exists(ws_path):
    raw = open(ws_path, 'rb').read()
    s = raw.replace(b'\r\n', b'\n').decode('utf-8')
    # Only fix the stub in the #else block (not the real implementation in #if block)
    # The stub is at the end of the file, after the #else at ~line 1238
    old_stub = (
        'CURL_EXTERN const struct curl_ws_frame *curl_ws_meta(struct Curl_easy *data)\n'
        '{\n'
        '  (void)data;\n'
        '  return NULL;\n'
        '}\n'
        '#endif /* USE_WEBSOCKETS */'
    )
    new_stub = (
        'CURL_EXTERN const struct curl_ws_frame *curl_ws_meta(CURL *curl)\n'
        '{\n'
        '  (void)curl;\n'
        '  return NULL;\n'
        '}\n'
        '#endif /* USE_WEBSOCKETS */'
    )
    if old_stub in s:
        s = s.replace(old_stub, new_stub)
        open(ws_path, 'w').write(s)
        print(f"Patched ws.c stub: {ws_path}")
    else:
        print(f"WARNING: ws.c stub pattern not found")
else:
    print(f"WARNING: ws.c not found at {ws_path}")



# --- Patch cf-socket.h: add missing netinet/in.h include ---
# sockaddr.h uses struct sockaddr_in which requires <netinet/in.h>.
# cf-socket.h includes sockaddr.h but doesn't ensure netinet/in.h is included first.
cfsocket_path = os.path.join(curl_src, 'cf-socket.h')
if os.path.exists(cfsocket_path):
    raw = open(cfsocket_path, 'rb').read()
    s = raw.replace(b'\r\n', b'\n').decode('utf-8')
    if '#include <netinet/in.h>' not in s:
        # Add after the first #include line
        s = re.sub(
            r'(#include [<"][^>"]+[>"][^\n]*\n)',
            r'\1#include <netinet/in.h>\n#include <sys/socket.h>\n',
            s, count=1
        )
        open(cfsocket_path, 'w').write(s)
        print(f"Patched: {cfsocket_path}")
    else:
        print(f"cf-socket.h already has netinet/in.h")
else:
    # Patch sockaddr.h directly as fallback
    sockaddr_path = os.path.join(curl_src, 'sockaddr.h')
    if os.path.exists(sockaddr_path):
        raw = open(sockaddr_path, 'rb').read()
        s = raw.replace(b'\r\n', b'\n').decode('utf-8')
        if '#include <netinet/in.h>' not in s:
            s = re.sub(
                r'(#include [<"][^>"]+[>"][^\n]*\n)',
                r'\1#include <netinet/in.h>\n#include <sys/socket.h>\n',
                s, count=1
            )
            open(sockaddr_path, 'w').write(s)
            print(f"Patched: {sockaddr_path}")


print("Done.")
